name: Deploy Blazor WASM to gh-pages branch

on:
  push:
    branches:
      - main        # Deploy when pushing to main
      - master      # Or master if that's your default
      - feature/web # Temporarily include your feature branch for testing

permissions:
  contents: write  # Need write permissions to push to gh-pages branch

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Publish Blazor WASM
      run: dotnet publish Traveler.Wasm.Client/Traveler.Wasm.Client.csproj -c Release -o publish
    
    - name: Debug - List publish directory
      run: |
        echo "Contents of publish directory:"
        ls -laR publish/
        echo ""
        echo "Finding index.html:"
        find publish -name "index.html" -type f
    
    - name: Change base tag in index.html
      run: |
        # Find the actual location of index.html and update it
        INDEX_PATH=$(find publish -name "index.html" -type f | head -n 1)
        echo "Found index.html at: $INDEX_PATH"
        sed -i 's|<base href="/" />|<base href="/KitchenDuplicateTraveler/" />|g' "$INDEX_PATH"
    
    - name: Add .nojekyll file
      run: |
        # Add .nojekyll to the same directory as index.html
        INDEX_DIR=$(dirname $(find publish -name "index.html" -type f | head -n 1))
        touch "$INDEX_DIR/.nojekyll"
    
    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: $(dirname $(find publish -name "index.html" -type f | head -n 1))
        publish_branch: gh-pages
        force_orphan: true