name: Release

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish Console App
      run: dotnet publish Traveler.Console/Traveler.Console.csproj --configuration Release --output ./publish --self-contained true --runtime win-x64 /p:PublishSingleFile=true

    - name: Get version
      id: version
      shell: pwsh
      run: |
        $branch = "${{ github.ref_name }}"
        $shortSha = "${{ github.sha }}".Substring(0, 7)
        $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
        
        if ($branch -eq "main") {
          $version = "v1.0.${{ github.run_number }}"
          $prerelease = "false"
        } elseif ($branch -eq "develop") {
          $version = "v1.0.${{ github.run_number }}-beta"
          $prerelease = "true"
        } else {
          $version = "v1.0.${{ github.run_number }}-$branch-$shortSha"
          $prerelease = "true"
        }
        
        echo "version=$version" >> $env:GITHUB_OUTPUT
        echo "prerelease=$prerelease" >> $env:GITHUB_OUTPUT

    - name: Create Release Archive
      shell: pwsh
      run: |
        $version = "${{ steps.version.outputs.version }}"
        Compress-Archive -Path ./publish/* -DestinationPath "KitchenDuplicateTraveler-$version-win-x64.zip"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref_type == 'tag' || github.ref_name == 'main' || github.ref_name == 'develop'
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: ${{ steps.version.outputs.prerelease }}
        files: |
          KitchenDuplicateTraveler-${{ steps.version.outputs.version }}-win-x64.zip
        body: |
          ## Kitchen Duplicate Traveler ${{ steps.version.outputs.version }}
          
          ### Changes
          - Built from branch: ${{ github.ref_name }}
          - Commit: ${{ github.sha }}
          
          ### Download
          Download the Windows executable below and run it to process your PBN files.
          
          ### Usage
          1. Download and extract the zip file
          2. Run `Traveler.Console.exe`
          3. Enter the path to your PBN file when prompted
          4. A PDF will be generated in the same directory as your PBN file